# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
