# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
